### ISSUE TITLE
Continuous Deployment

### ISSUE THREAD

**Issue by hueyy** [uclapi/ucl-assistant-app#11]
We might want to add continuous deployment via Travis:

* We could automatically publish `master` to a production release channel
* And automatically publish PRs to individual release channels for testing purposes

**Comment by ChristopherHammond13** [comment]
Sounds great to me! I'm not sure how to do this with an Android/iOS app though. Can we set up devices in Expo to be Dev channel ones, and enroll testers manually? It would also be great if we could roll out new releases to the store when needed with version bumps. I actually know nothing about mobile application DevOps so there's probably a lot to discuss all round. If we need infrastructure for this I'll be more than happy to support it though.

**Comment by hueyy** [comment]
Hmmm. I've never done continuous native deployment to any degree of satisfaction either. The main issues are the many dependencies required (for compiling, for signing, for uploading, etc.). Furthermore, for iOS, the deployment machine must be running macOS with Xcode installed, which is not a common VPS offering.

At this stage at least, I was thinking more of just automation of the `expo publish` command with an appropriate [`--release-channel` parameter](https://docs.expo.io/versions/latest/distribution/release-channels/). Basically, automation of what I was manually doing in my PRs [here](https://github.com/uclapi/ucl-assistant-app/pull/14#issuecomment-464409746) and [here](https://github.com/uclapi/ucl-assistant-app/pull/13#issuecomment-464410277)

This can likely be done through Travis without any additional infrastructure as far as I can see, and will allow anyone with the Expo app installed to test the version built from any given PR (or the latest version of master).

This isn't perfect - there might be things that will only crop up when we build and run the actual apk or ipa (e.g. things that use deep linking, splash-screen & icon-related matters, etc), but this should catch the vast majority of issues.
