### ISSUE TITLE
Happening Now

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/ucl-assistant-app#112]
It would be awesome if we could have lectures which are currently in progress listed as 'happening now', similar to 'past events' that we have now. The only concern is how often this page is updated (e.g. would it require a manual refresh to update this?)

**Comment by hueyy** [comment]
This is a great idea. What about a label on the event in progress (e.g. like the LIVE label).

I don't think we'll need a manual refresh so that's fine.

**Comment by hueyy** [comment]
Resolved by #115
