### ISSUE TITLE
Study spaces map only show in landscape mode?

### ISSUE THREAD

**Issue by zipy124** [uclapi/ucl-assistant-app#130]
This seems weird surely they should show in both orientations

**Comment by hueyy** [comment]
<img src="https://user-images.githubusercontent.com/6523121/55588213-14730700-5725-11e9-9f77-0d789fc9a80b.jpg" width="200" />

Because it's ugly and this app only contains pretty things. We take a paternalistic approach and unilaterally decide what's best for our users.

**Comment by zipy124** [comment]
Is there any way we can just zoom in by default in portrait mode. switching orientation I'd argue is also pretty ugly and annoying. Or just rotate the map and not the UI?

**Comment by hueyy** [comment]
<img src="https://user-images.githubusercontent.com/6523121/55588585-1093b480-5726-11e9-82d0-35100b95b938.jpg" width="200" />

Something like this by default? It's difficult to get the default zoom right because the maps all differ in sizes and aspect ratios, but roughly this?
