### ISSUE TITLE
room hotlink on timetable links to search

### ISSUE THREAD

**Issue by zipy124** [uclapi/ucl-assistant-app#132]
Is there any way to get a room hotlink to link directly to the room, instead of a search for the room? this seems much nicer?

**Comment by hueyy** [comment]
This is possible in principle but is trickier in reality. The RoomDetail screen doesn't fetch further info but simply displays the data fetched on the RoomSearch screen. Although all the necessary data is technically available on the TimetableDetail screen it's all over the place and in a different format. But fair point, linking directly to RoomDetail should be the way to go. I'll take a stab at it in a bit.

**Comment by hueyy** [comment]
Oh slight issue 😢: can't do this without the `roomid`, `siteid` and `classification` being passed from the uclapi `/timetable/personal` endpoint.

**Comment by zipy124** [comment]
I think all we need is the siteid, since roomname and siteid should be uniquely identifying

**Comment by zipy124** [comment]
Alternatively we can make /rooms take a sitename

**Comment by hueyy** [comment]
That would work, but would require me to redo a fair bit of the rooms-related code because the RoomDetail screen right now doesn't independently fetch data on its own, it just receives and displays the search result from the RoomSearch screen. 

The RoomDetail screen would need to fetch

**Comment by zipy124** [comment]
We'll adjust timetable accordingly then, no reason not to provide more data i guess.

**Comment by hueyy** [comment]
In the meantime I've put in a slightly hackish solution that will auto-navigate to the first result on the screen (if there is only 1 result and only when coming from TimetableDetail).
