### ISSUE TITLE
Show Free Seats on Study Spaces Screen

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/ucl-assistant-app#2]
At the moment the app says, for example, `Quite busy (235/282)`

It's probably more beneficial to say something like `Quite busy (47/282 seats free)`
I'm not sure if it'll fit in the box though? We might need to experiment a bit with the text there, but I think it'll make it more clear to users what the numbers mean.

**Comment by hueyy** [comment]
#14 fixes this
