### ISSUE TITLE
Clicking on People tab crashes and restarts app

### ISSUE THREAD

**Issue by zipy124** [uclapi/ucl-assistant-app#294]
the stacktrace shows '''Uncaught Error: TypeError: TypeError: null is not an object (evaluating 't.name'.

**Comment by hueyy** [comment]
I haven't been able to reproduce this on my own device. Is there a particular state that could have triggered this? E.g. an existing search term, etc.?

**Comment by hueyy** [comment]
Probably local state issue. Will handle that better (#299 and #300).
