### ISSUE TITLE
Library Rooms Availability

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/ucl-assistant-app#4]
On each study space's detail screen, it would be cool if we could list each map (which will be far easier to implement than the live maps) with a view that looks a bit like, for UCL Main Library (as an example):
```
Rooms
1st West: 17 seats free (total: 184)
1st East: 14 seats free (total: 84)
...
etc.
```

We could have each map name as a subtitle and put a live map underneath it (#3) but I think this will be too cramped on smaller (< 5") devices. For now, the text is probably enough.

**Comment by hueyy** [comment]
Addressed by #16
