### ISSUE TITLE
App never finished loading if switching apps before startup.

### ISSUE THREAD

**Issue by zipy124** [uclapi/ucl-assistant-app#412]
**Describe the bug**
When starting up the app, if you switch apps before it finishes loading, then switch back it will never load.

**To Reproduce**
1. Open app
2. switch app before finishes loading
3. switch back
4. note app is now stuck

**Expected behavior**
App should re-load or continue loading.

**Screenshots**
![Screenshot_20191130-132945_UCL_Assistant](https://user-images.githubusercontent.com/6547350/69901160-16ee3500-1376-11ea-9f2c-879b7d8411e1.png)

**Please provide the following information:**
 - Device: OnePlus 3T
 - OS: LineageOS 16.0 Android 9.0
 - Release Channel production-5.0.0

**Additional context**

**Comment by hueyy** [comment]
Fixed

[img](https://i.imgur.com/xzcwSwI.gif)
