### ISSUE TITLE
App crashes on stratup

### ISSUE THREAD

**Issue by zipy124** [uclapi/ucl-assistant-app#501]
**Describe the bug**
App won't start

**Please provide the following information:**
 - Device: One Plus 3T
 - OS: LineageOS 16.0
 - Release Channel [check Settings]

**Comment by hueyy** [comment]
I believe https://github.com/uclapi/ucl-assistant-app/commit/731219d09246f19eb411344ca353bd1ce3088360 fixes this. There was a mismatch in the versions of a few dependencies.
