### ISSUE TITLE
[High Priority] Privacy Guidelines

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/ucl-assistant-app#57]
In order to publish in the Play Store, we have to abide by the following rules: https://play.google.com/about/privacy-security-deception/personal-sensitive/

This means that on the Splash screen we should have a notice that says something like:
```
By signing into this app, you accept that certain data will be required to ensure the app functions correctly.
```
We should also tell them exactly which organisations data is sent to:
- UCL
- UCL API [i.e. us]
- Sentry for crash information

Plus, we should point out that updates may be downloaded automatically via Expo as they are made available. They will be informed if updates require a change in the privacy policy.
The app is subject to UCL's standard Privacy Policy: https://www.ucl.ac.uk/legal-services/privacy/general-privacy-policy

**Comment by hueyy** [comment]
Resolved by #58
