### ISSUE TITLE
study space graph x axis is off?

### ISSUE THREAD

**Issue by zipy124** [uclapi/ucl-assistant-app#89]
You can see here 5:30pm seems to be after 6pm?

![Screenshot_20190312-173137_UCL_Assistant](https://user-images.githubusercontent.com/6547350/54243229-8ccc1b00-451f-11e9-9e88-67969d1e56d6.png)

**Comment by hueyy** [comment]
[![time is not linear](https://img.youtube.com/vi/q2nNzNo_Xps/0.jpg)](https://youtu.be/q2nNzNo_Xps?t=4)
