### ISSUE TITLE
Switch to OpenStreetMap

### ISSUE THREAD

**Issue by greenfrogs** [uclapi/ucl-assistant-app#968]
OpenStreetMaps is now more accurate in and around UCL than Google Maps, it includes paths through and around Portico. This would also help to become independent from Google.

https://www.openstreetmap.org/search?query=UCL#map=18/51.52400/-0.13189

**Comment by hueyy** [comment]
Yeah OpenStreetMaps looks pretty good. Thanks for suggesting this.

**Comment by greenfrogs** [comment]
This has been implemented in the new flutter version
