### ISSUE TITLE
Filtering Doesn't Work On Rooms Screen

### ISSUE THREAD

**Issue by nayanadasgupta** [uclapi/ucl-assistant-app#988]
**Describe the bug**

Attempting to filter using the dropdown selector on the rooms screen does not have any affect on the rooms shown on the list. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the Rooms screen.
2. Select any building e.g. Roberts Building.
3. See that list of vacant rooms has not changed from all buildings version.

**Expected behaviour**

Rooms list would filter based on selected building to only show vacant rooms inside a specific building.

**Device and App Release Information:**
 - Device: iPhone 8
 - OS: iOS14.1
 - Release Channel: production-8.00

**Comment by hueyy** [comment]
Looks like a regression. Will look into this.
