### ISSUE TITLE
No timetable showing

### ISSUE THREAD

**Issue by dmbrwr** [uclapi/ucl-assistant-app#991]
Timetable does not appear for my account 

1. Login
2. Go to timetable
3. No timetable showing for any week past, present or future
4. Says 'nothing scheduled this week. Take it easy!'

**Expected behavior**
A timetable that matches the UCL timetable website

iPhone SE 2020
iOS 14.2
Release channel: production-8.0.0

**Comment by hueyy** [comment]
Sorry the timetable isn't working for you. Can you email isd.apiteam@ucl.ac.uk with your UCL username (the 6 alphanumeric characters before your email address, e.g. zctjsp1) and a copy of your timetable from [timetable.ucl.ac.uk](https://timetable.ucl.ac.uk)?

To get a PDF copy of your timetable:

1. Click "personal"
2. Click the "Change Display" tab
3. Select "Full Year"
4. Click "Print"
5. Click "Print this page"
6. Print the timetable to PDF

This'll help us identify which particular classes from which modules are missing.
